/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AccountIdInboxImport } from './routes/$accountId.inbox'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIdInboxRoute = AccountIdInboxImport.update({
  id: '/$accountId/inbox',
  path: '/$accountId/inbox',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$accountId/inbox': {
      id: '/$accountId/inbox'
      path: '/$accountId/inbox'
      fullPath: '/$accountId/inbox'
      preLoaderRoute: typeof AccountIdInboxImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$accountId/inbox': typeof AccountIdInboxRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$accountId/inbox': typeof AccountIdInboxRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$accountId/inbox': typeof AccountIdInboxRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$accountId/inbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$accountId/inbox'
  id: '__root__' | '/' | '/$accountId/inbox'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIdInboxRoute: typeof AccountIdInboxRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIdInboxRoute: AccountIdInboxRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$accountId/inbox"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$accountId/inbox": {
      "filePath": "$accountId.inbox.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
